
services:
  openhands:
    build:
      context: ./
      dockerfile: ./containers/app/Dockerfile
    image: docker.all-hands.dev/all-hands-ai/openhands:0.24
    container_name: openhands
    env_file: 
      - path: ./env/openhands.env
        required: true   
    environment:
      - SANDBOX_USER_ID=501
      - WORKSPACE_BASE=${WORKSPACE_BASE}
      - WORKSPACE_MOUNT_PATH=${WORKSPACE_BASE}
      - LOG_ALL_EVENTS=${LOG_ALL_EVENTS}
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=${SANDBOX_RUNTIME_CONTAINER_IMAGE}
    ports:
      - "3001:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openhands-state:/.openhands-state
      - ${WORKSPACE_BASE}:/opt/workspace_base
    pull_policy: build
    stdin_open: true
    tty: true
